language: node_js
node_js:
  - "8"
  - "9"

cache: npm

install: npm
script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: npm publish
      deploy:
        provider: npm publish
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true

